### ISSUE TITLE
Allow keystroke to turn on port code timings in visualizer

### ISSUE THREAD

**Issue by henrymj** [AwhVogelLab/preprocessing_pypeline#20]
EEGLab shows when all port codes occur in the trial epochs, which is helpful for making sure that all of the timings are correct. Right now we do not have that, but I think it would be useful to add.

I'd suggest adding the key "P" to the visualizer, which would add vertical lines and port code labels at the top of the plots.

**Comment by dsuplica** [comment]
can do this by looking at port code timings in raw eeg and comparing those to the filtered and preprocessed ones
